import Header from "../../components/Header/Header";
import { useEffect } from "react";
import { Link } from "react-router-dom";

const Tos = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <>
            <div className="info-header">
                <Header
                    pIntro="Legal Information"
                    h1Text="Terms of Service"
                />
            </div>
            <div className="wall-text-bg">
                <main className="wall-text-wrapper">
                    <p>Last updated: November 29, 2022</p>
                    <div>
                        <p>These Stark Lab Terms of Service (this “<strong>Agreement</strong>”) is entered into by and between Stark Lab, Inc. (“<strong>Stark Lab</strong>”) and the entity or person placing an order for or accessing the Stark Lab Services (“<strong>Customer</strong>” or “<strong>you</strong>”). This Agreement consists of the terms and conditions set forth below, any exhibits or addenda identified below and any Order Forms. If you are accessing or using the Stark Lab Services on behalf of your company, you represent that you are authorized to accept this Agreement on behalf of your company, and all references to “you” or “Customer” reference your company.</p>
                        <p>Please note that Stark Lab may modify the terms and conditions of this Agreement in accordance with Section 12.9 (Amendments; Waivers).</p>
                        <p>BY INDICATING YOUR ACCEPTANCE OF THIS AGREEMENT OR ACCESSING OR USING THE STARK LAB SERVICES, YOU ARE AGREEING TO BE BOUND BY ALL TERMS, CONDITIONS AND NOTICES CONTAINED OR REFERENCED IN THIS AGREEMENT. IF YOU DO NOT AGREE TO THIS AGREEMENT, PLEASE DO NOT USE THE STARK LAB SERVICES. FOR CLARITY, EACH PARTY EXPRESSLY AGREES THAT THIS AGREEMENT IS LEGALLY BINDING UPON IT.</p>
                    </div>
                    <section>
                        <h2>1. Definitions</h2>
                        <p>1.1 - “<strong>Stark Lab Code</strong>” means the software plugins, software application, and other software code provided by Stark Lab to enable use of the Stark Lab Service.</p>
                        <p>1.2 - “<strong>Stark Lab Service</strong>” means Stark Lab’s software-as-a-service platform and related development tools for website and mobile application accessibility.</p>
                        <p>1.3 - “<strong>Stark Lab Technology</strong>” means the Stark Lab Service, any other Stark Lab products and services, and all related or underlying documentation, technology, code, Aggregate/Anonymous Data, logs, product usage data, know-how, logos, materials, and templates (including anything delivered as part of support or other services), and any updates, modifications or derivative works of any of the foregoing (including as may incorporate any Feedback).</p>
                        <p>1.4 - “<strong>Confidential Information</strong>” means code, inventions, know-how, product plans, and technical and financial information exchanged under this Agreement, that is identified as confidential at the time of disclosure or should reasonably be considered confidential based on the circumstances surrounding the disclosure and the nature of the information disclosed.</p>
                        <p>1.5 - “<strong>Customer Data</strong>” means any data collected from or by the Stark Lab Service on behalf of Customer and any data or content that Customer provides to the Stark Lab Service.</p>
                        <p>1.6 - “<strong>Customer Properties</strong>” means Customer’s website, mobile applications or other properties that utilize the Stark Lab Service.</p>
                        <p>1.7 - “<strong>Order Form</strong>” means any Stark Lab ordering documentation, online sign-up, or subscription flow that references this Agreement.</p>
                        <p>1.8 - “<strong>Term</strong>” means the initial term for the applicable Stark Lab Service specified on an Order Form, and each subsequent renewal term (if any).</p>
                        <p>1.9 - “<strong>Third-Party Product</strong>” means any content, documentation, applications, integrations, software, code, online services, systems, other products not developed by Stark Lab.</p>
                    </section>
                    <section>
                        <h2>2. Account Registration and Use</h2>
                        <p>Customer may need to register for a Stark Lab account in order to use the Stark Lab Service. Account information must be accurate, current, and complete, and will be governed by Stark Lab’s Privacy Policy (currently available at 
                            &nbsp;<Link to="/privacy">https://www.getstark.co/privacy/</Link>). Customer agrees to keep this information up-to-date so that Stark Lab may send notices, statements, and other information by email or through Customer’s account. Customer must ensure that any user IDs, passwords, and other access credentials for the Stark Lab Service are kept strictly confidential and not shared with any unauthorized person. Customer will be responsible for any and all actions taken using its and its users’ accounts, passwords or access credentials. Customer must notify Stark Lab promptly of any breach of security or unauthorized use of its account.
                        </p>
                    </section>
                    <section>
                        <h2>3. Use Rights</h2>
                        <p>3.1 - <strong>Use of Stark Lab Services</strong>. Subject to the terms and conditions of this Agreement, Stark Lab grants Customer a non-exclusive, non-transferable, non-sublicensable right and license during the applicable Term to access and use the Stark Lab Service, solely for Customer’s internal business purposes. The Stark Lab Service may require installation of certain Stark Lab Code within Customer’s development environment. In these cases, subject to the same conditions above, the rights granted in this Section further include the right to install and use the relevant Stark Lab Code.</p>
                        <p>3.2 - <strong>General Restrictions</strong>. Customer must not (and must not allow any third party to): (i) rent, lease, copy, transfer, mirror, resell, sublicense, lease, time-share, distribute, or otherwise provide access to any portion of the Stark Lab Service to a third party; (ii) modify or create a derivative work of the Stark Lab Service or any portion of it; (iii) reverse engineer, disassemble, decompile, translate, or otherwise seek to obtain or derive the source code, underlying ideas, algorithms, file formats, or non-public APIs to any Stark Lab Service (including Stark Lab Code), except to the extent expressly permitted by applicable law and then only with advance notice to Stark Lab; (iv) break or circumvent any security measures, rate limits, or usage tracking (such as event tracking) of the Stark Lab Service; (v) access the Stark Lab Service for the purpose of building a competitive product or service or copying its features or user interface; (vi) use the Stark Lab Service for purposes of product evaluation, benchmarking, performance testing, or comparative analysis intended for publication; (vii) use the Stark Lab Service in violation of applicable laws (including to conduct, promote or encourage any criminal or illegal activity or enterprise); or (viii) remove or obscure any proprietary, copyright, or other notices contained in the Stark Lab Service, including in any reports or output obtained from the Stark Lab Service.</p>
                        <p>3.3 - <strong>Customer Responsibilities</strong>. Stark Lab Service provides tools for improving accessibility for the Customer Properties. However, Customer is solely responsible for the decisions and choices it makes while using the Stark Lab Service, and Stark Lab does not guarantee that the Customer Properties will necessarily comply with all applicable legal requirements through use of the Stark Lab Service. The Stark Lab Service, including the recommendations made therein, cannot be regarded as, nor does it substitute, any legal advice given by a professional or expert and Customer should consult with their own legal counsel as necessary.</p>
                        <p>3.4 - <strong>Beta Releases and Free Access Subscriptions</strong>. Stark Lab may provide Customer with a Stark Lab Service for free or on a trial basis (a “<strong>Free Access Subscriptions</strong>”) or with “alpha”, “beta”, or other early-stage Stark Lab Services, integrations, or features (“<strong>Beta Releases</strong>”), which are optional for Customer to use. Stark Lab makes no promises that future versions of Beta Releases or Free Access Subscriptions will be released or will be made available under the same commercial or other terms. Stark Lab may terminate Customer’s right to use any Free Access Subscriptions or Beta Releases at any time in Stark Lab’s sole discretion, without liability. WITH RESPECT TO BETA RELEASES, CUSTOMER ACKNOWLEDGES AND AGREES THAT BETA RELEASES MAY NOT BE COMPLETE OR FULLY FUNCTIONAL AND MAY CONTAIN BUGS, ERRORS, OMISSIONS, AND OTHER PROBLEMS FOR WHICH STARK LAB WILL NOT BE RESPONSIBLE. ACCORDINGLY, ANY USE OF BETA RELEASES ARE AT CUSTOMER’S SOLE RISK NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN.</p>
                    </section>
                    <section>
                        <h2>4. Customer Data</h2>
                        <p>4.1 - <strong>Rights in Customer Data</strong>. As between the parties, Customer retains all right, title, and interest (including any intellectual property rights) in and to the Customer Data. Customer grants Stark Lab a non-exclusive, worldwide, royalty-free right to collect, use, modify and process Customer Data solely: (i) to provide the Stark Lab Service and related services to Customer and (ii) to generate separate anonymous data sets about product usage that do not identify Customer or its employees and that are stripped of all persistent identifiers (such as name, email address, etc.) (“<strong>Aggregate/Anonymous Data</strong>”).</p>
                        <p>4.2 - <strong>Security</strong>. Stark Lab will implement appropriate technical and organizational security measures designed to protect Customer Data in the Stark Lab Service against unauthorized or unlawful processing, accidental or unlawful destruction, accidental loss or alteration, and unauthorized disclosure or access.</p>
                    </section>
                    <section>
                        <h2>5. Fees and Payment</h2>
                        <p>5.1 - <strong>Fees</strong>. To the extent the Stark Lab Services are made available for a fee, Customer agrees to pay all fees in United States Dollars. Stark Lab’s fees are exclusive of all taxes, and Customer must pay any applicable sales, use, VAT, GST, excise, withholding, or similar taxes or levies, whether domestic or foreign, other than taxes based on the income of Stark Lab. Except as expressly provided in this Agreement, payments are non-refundable and non-creditable and payment obligations non-cancellable.</p>
                        <p>5.2 - <strong>Credit Card Payment Terms</strong>. If Customer has signed up to pay via credit card, Customer shall provide its payment information to Stark Lab or to one of its payment processors. Customer represents to Stark Lab that is the authorized user of the card, PIN, key or account associated with that payment instrument, and Customer authorizes Stark Lab to charge its credit card or other payment instrument for any funds or other fees (including transaction and credit card fees) incurred by you in connection with the Stark Lab Services. In addition, Customer is solely responsible for either (a) enabling auto-recharge on Customer’s payment instrument or (b) ensuring that Customer’s payment instrument has a sufficient positive balance to cover all fees due. If, for any reason, Customer has a negative balance on its account(s), then Stark Lab reserves the right to suspend access to the Stark Lab Services.</p>
                        <p>5.3 - <strong>Invoicing Payment Terms</strong>. If the corresponding Order Form specifies that Customer is to pay via invoice, Stark Lab shall invoice Customer in accordance with the payment terms set forth in the Order Form. Except as otherwise set forth in an Order Form, Customer will make all of the undisputed fees hereunder within seven (7) days of the date of the invoice. If Customer is overdue on any payment of undisputed fees and fails to pay within ten (10) business days of a written notice, then Stark Lab may assess, and Customer agrees to pay a late fee of either 1.5% per month, or the maximum amount allowable by applicable law, whichever is less.</p>
                        <p>5.4 - <strong>Disputes</strong>. Customer must notify Stark Lab in writing of any good-faith invoice dispute within twenty (20) days of the applicable invoice date and reasonably cooperate with Stark Lab in resolving any dispute. If the parties are unable to resolve a dispute within ten (10) days of Customer’s notice, each party will have the right to seek any remedies it may have under this Agreement, at law or in equity, irrespective of any provision in this Agreement that would limit seeking these remedies on account of a payment dispute. For clarity, any undisputed amounts must be paid in full in accordance with this Section.</p>
                    </section>
                    <section>
                        <h2>6. Term and Termination</h2>
                        <p>6.1 - <strong>Term</strong>. This Agreement is effective as of the Effective Date and continues until terminated. Either party may terminate this Agreement with thirty (30) days’ advance written notice if all Terms for the Stark Lab Service(s) have expired or are terminated as expressly permitted in this Agreement.</p>
                        <p>6.2 - <strong>Renewals</strong>. By executing an Order Form for purchase of a Stark Lab Service, Customer is agreeing to pay applicable fees for the entire Term. Customer cannot cancel or terminate this Agreement except as expressly permitted by Section 6.4 (Termination for Cause) and Section 10.1 (Limited Warranty). If no start date is specified on the applicable Order Form, the Term starts when Customer first obtains access to the Stark Lab Service. Each Term will automatically renew for additional successive renewal terms with the same length as the initial term unless: (i) otherwise stated on the applicable Order Form; or (ii) either party gives written notice of non-renewal at least thirty (30) days before the end of the then-current Term.</p>
                        <p>6.3 - <strong>Suspension of Service</strong>. Stark Lab may suspend Customer’s access to the Stark Lab Service(s) if Customer’s account is overdue and Customer fails to pay amounts due within ten (10) days of notice by Stark Lab, subject to Section 5.4 (Disputes). Stark Lab may also suspend Customer’s access to the Stark Lab Service(s) if it determines that suspension is necessary to prevent harm or liability to other customers or third parties, or to preserve the security, stability, availability or integrity of the Stark Lab Service.</p>
                        <p>6.4 - <strong>Termination for Cause</strong>. Either party may terminate this Agreement, including any related Order Form, if the other party: (i) fails to cure any material breach of this Agreement (including a failure to pay undisputed fees) within thirty (30) days after written notice detailing the breach; (ii) ceases operation without a successor; or (iii) if permitted by applicable law, seeks protection under any bankruptcy, receivership, trust deed, creditors’ arrangement, composition, or comparable proceeding, or if any of these proceedings are instituted against that party (and not dismissed within sixty (60) days thereafter).</p>
                        <p>6.5 - <strong>Effect of Termination</strong>. Upon any expiration or termination of this Agreement or an Order Form, Customer’s license rights terminate and it must promptly: (a) stop using the applicable Stark Lab Service(s) (including any related Stark Lab Technology); (b) delete (or, at Stark Lab’s request, return) any and all copies of the Stark Lab Code, any Stark Lab documentation, passwords or access codes, and any other Stark Lab Confidential Information in Customer’s possession, custody, or control. If Stark Lab terminates this Agreement for cause as provided in Section 6.4 (Termination for Cause), any payments for the remaining portion of the Term will become due and must be paid immediately by Customer. If Customer terminates this Agreement for cause as provided in Section 6.4 (Termination for Cause), Customer will receive a refund of any fees it has pre-paid for the terminated portion of the applicable Term. Except where this Agreement specifies an exclusive remedy, all remedies under this Agreement, including termination or suspension, are cumulative and not exclusive of any other rights or remedies that may be available to a party.</p>
                        <p>6.6 - <strong>Survival</strong>. The following Sections survive any expiration or termination of this Agreement: 1 (Definitions); 2 (Account Registration and Use); 3.2 (General Restrictions); 3.3 (Beta Releases and Free Access Subscriptions); 4.1 (Rights in Customer Data); 5 (Fees and Payment); 6 (Term and Termination); 7 (Confidential Information); 8 (Stark Lab Technology); 9 (Indemnification); 10 (Disclaimers); 11 (Limitations of Liability); and 12 (General).</p>
                    </section>
                    <section>
                        <h2>7. Confidential Information</h2>
                        <p>7.1 - <strong>Confidentiality Obligation</strong>. Each party (as the receiving party) must: (i) hold in confidence and not disclose the other party’s Confidential Information to third parties except as permitted by this Agreement; and (ii) only use the other party’s Confidential Information to fulfill its obligations and exercise its rights under this Agreement. Each party may share the other party’s Confidential Information with its employees, agents or contractors having a legitimate need to know (which, for Stark Lab, includes the subcontractors referenced in Section 12.4), provided that the party remains responsible for any recipient’s compliance with the terms of this Section 7 and that these recipients are bound to confidentiality obligations no less protective than this Section.</p>
                        <p>7.2 - <strong>Exclusions</strong>. These confidentiality obligations do not apply to (and Confidential Information does not include) information that: (i) is or becomes public knowledge through no fault of the receiving party; (ii) was known by the receiving party before it received the Confidential Information; (iii) is rightfully obtained by the receiving party from a third party without breach of any confidentiality obligation; or (iv) is independently developed by the receiving party without using the disclosing party’s Confidential Information. A party may also disclose the other party’s Confidential Information to the extent required by law or court order, provided it gives advanced notice (if permitted by law) and cooperates in any effort by the other party to obtain confidential treatment for the information.</p>
                        <p>7.3 - <strong>Remedies</strong>. The parties acknowledge that disclosing Confidential Information may cause substantial harm for which damages alone may be an insufficient remedy, and so on breach of this Section, each party is entitled to seek appropriate equitable relief in addition to any other remedies it may have at law.</p>
                    </section>
                    <section>
                        <h2>8. Stark Lab Technology</h2>
                        <p>8.1 - <strong>Ownership and Updates</strong>. This is a term-limited agreement for access to and use of the Stark Lab Service. Customer acknowledges that it is obtaining only a limited right to use the Stark Lab Service and no ownership rights are transferred to Customer under this Agreement. Stark Lab (or its suppliers) retain all rights, title and interest (including all intellectual property rights) in and to all Stark Lab Technology, which is deemed Stark Lab’s Confidential Information, and reserves any licenses not specifically granted in this Agreement. Other than the Stark Lab Code, the Stark Lab Service is offered as an online, hosted product. Accordingly, Customer acknowledges and agrees that it has no right to obtain a copy of the software behind any Stark Lab Service. In addition, Stark Lab may collect learnings, logs, and data regarding the performance and use of the Stark Lab Service, and that Stark Lab may make updates, bug fixes, modifications or improvements to the Stark Lab Service from time-to-time.</p>
                        <p>8.2 - <strong>Feedback</strong>. If Customer elects to provide any suggestions, comments, improvements, information, ideas or other feedback or related materials to Stark Lab (collectively, “Feedback”), Customer hereby grants Stark Lab a worldwide, perpetual, non-revocable, sublicensable, royalty-free right and license to use, copy, disclose, license, distribute, and exploit any Feedback in any format and in any manner without any obligation, payment, or restriction based on intellectual property rights or otherwise, however Stark Lab will not identify Customer as the source of the Feedback. Nothing in this Agreement limits Stark Lab’s right to independently use, develop, evaluate, or market products, whether incorporating Feedback or otherwise.</p>
                    </section>
                    <section>
                        <h2>9. Indemnification</h2>
                        <p>Customer agrees to defend Stark Lab from and against any third-party claim to the extent resulting from any Customer Properties, its negligence, willful misconduct or breach of this Agreement. Customer will indemnify and hold Stark Lab harmless from and against any damages and costs awarded against Stark Lab or agreed in settlement by Customer (including reasonable attorney’s fees) that result from these third-party claims. Customer must not settle any claim without Stark Lab’s prior written consent if the settlement would require Stark Lab to admit fault, pay amounts that Customer must pay under this Agreement, or take or refrain from taking any action. Stark Lab may participate in a claim through counsel of its own choosing at its own expense and Customer and Stark Lab will reasonably cooperate on the defense.</p>
                    </section>
                    <section>
                        <h2>10. Disclaimers</h2>
                        <p>ALL STARK LAB TECHNOLOGY AND RELATED SERVICES ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS. NEITHER STARK LAB NOR ITS SUPPLIERS MAKE ANY OTHER WARRANTIES, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. STARK LAB MAKES NO REPRESENTATION, WARRANTY OR GUARANTEE THAT STARK LAB TECHNOLOGY WILL MEET CUSTOMER’S REQUIREMENTS OR EXPECTATIONS, OR THAT STARK LAB TECHNOLOGY WILL BE TIMELY, UNINTERRUPTED OR ERROR-FREE. THE DISCLAIMERS IN THIS SECTION WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT. CUSTOMER MAY HAVE OTHER STATUTORY RIGHTS. HOWEVER, ANY STATUTORILY REQUIRED WARRANTIES UNDER APPLICABLE LAW, IF ANY, WILL BE LIMITED TO THE SHORTEST PERIOD AND MAXIMUM EXTENT PERMITTED BY LAW.</p>
                    </section>
                    <section>
                        <h2>11. Limitations of Liability</h2>
                        <p>11.1 - <strong>Consequential Damages Waiver</strong>. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY LOSS OF USE, LOST OR INACCURATE DATA, INTERRUPTION OF BUSINESS, LOST PROFITS, COSTS OF DELAY, REPUTATIONAL HARM, OR ANY INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES OF ANY KIND HOWEVER CAUSED, EVEN IF INFORMED IN ADVANCE OF THE POSSIBILITY OF THESE DAMAGES.</p>
                        <p>11.2 - <strong>Liability Cap</strong>. STARK LAB’S TOTAL LIABILITY WILL NOT EXCEED IN AGGREGATE THE AMOUNT ACTUALLY PAID OR PAYABLE BY CUSTOMER TO STARK LAB FOR THE APPLICABLE STARK LAB SERVICE OR RELATED SERVICES IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, EXCEPT THAT THIS SECTION 11.2 DOES NOT APPLY TO: (i) DEFENSE COSTS AND DAMAGES PAYABLE BY AN INDEMNIFYING PARTY TO THIRD PARTIES UNDER SECTION 9 (INDEMNIFICATION); AND (ii) CUSTOMER’S PAYMENT OBLIGATIONS AS EXPRESSLY PROVIDED IN THIS AGREEMENT. FOR FREE ACCESS SUBSCRIPTIONS OR BETA RELEASES, STARK LAB’S TOTAL LIABILITY WILL NOT EXCEED IN AGGREGATE FIFTY U.S. DOLLARS ($50 US).</p>
                        <p>11.3 - <strong>Exceptions</strong>. NOTWITHSTANDING THE FOREGOING, NONE OF THE LIMITATIONS IN THIS SECTION 11 EXCLUDES EITHER PARTY’S LIABILITY FOR FRAUD OR FOR DEATH OR PERSONAL INJURY TO THE EXTENT CAUSED BY A PARTY’S NEGLIGENCE. IN ADDITION, THE LAWS IN SOME JURISDICTIONS MAY NOT ALLOW SOME OF THE LIMITATIONS OF LIABILITY IN THIS SECTION. IF ANY OF THESE LAWS IS FOUND TO APPLY TO THIS AGREEMENT, THIS SECTION 11 WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
                        <p>11.4 - <strong>Failure of Essential Purpose</strong>. EACH PARTY ACKNOWLEDGES AND AGREES THAT THIS SECTION 11 IS A FUNDAMENTAL BASIS OF THE BARGAIN AND A REASONABLE ALLOCATION OF RISK BETWEEN THE PARTIES AND WILL SURVIVE AND APPLY TO ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT, ANY STARK LAB TECHNOLOGY OR ANY RELATED SERVICES, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE), EVEN IF ANY LIMITED REMEDY IN THIS AGREEMENT IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
                    </section>
                    <section>
                        <h2>12. General</h2>
                        <p>12.1 - <strong>Governing Law; Jurisdiction and Venue</strong>. This Agreement is governed by the laws of the State of Delaware and the United States, without regard to choice or conflict of law rules thereof. The exclusive jurisdiction and venue for actions related to the subject matter of this Agreement are the state and federal courts located in Delaware, and both parties submit to the personal jurisdiction of these courts.</p>
                        <p>12.2 - <strong>Assignment</strong>. This Agreement will bind and inure to the benefit of each party’s permitted successors and assigns. Neither party may assign this Agreement without the other party’s advanced written consent, except that each party may assign this Agreement without consent in connection with a merger, reorganization, acquisition, or other transfer of all or substantially all of its assets or voting securities. Any attempt to transfer or assign this Agreement except as expressly authorized under this Section will be void.</p>
                        <p>12.3 - <strong>Notices</strong>. Any notice or communication under this Agreement must be in writing. Customer must send any notices under this Agreement (including breach notices and warranty and indemnity claims) to Stark Lab, in English to support @getstark.co. Stark Lab may send notices to the email addresses on Customer’s account or, at Stark Lab’s option, to Customer’s last-known postal address. Stark Lab may also provide operational notices regarding the Stark Lab Service or other business-related notices through conspicuous posting of the notice on Stark Lab’s website or the Stark Lab Service. Each party consents to receiving electronic notices. Stark Lab is not responsible for any automatic filtering Customer or its network provider may apply to email notifications.</p>
                        <p>12.4 - <strong>Subcontractors</strong>. Stark Lab may use subcontractors and permit them to exercise the rights granted to Stark Lab in order to provide the Stark Lab Service and related services under this Agreement. These subcontractors may include, for example, Stark Lab’s hosting providers. However, subject to all terms and conditions of this Agreement, Stark Lab will remain responsible for: (i) compliance of its subcontractors with the terms of this Agreement; and (ii) the overall performance of the Stark Lab Services if and as required under this Agreement.</p>
                        <p>12.5 - <strong>Independent Contractors</strong>. The parties to this Agreement are independent contractors, and this Agreement does not create a partnership, joint venture, employment, franchise, or agency relationship. Neither party has the power to bind the other or incur obligations on the other party’s behalf without the other party’s prior written consent.</p>
                        <p>12.6 - <strong>Force Majeure</strong>. Neither party will be liable for any delay or failure to perform its obligation under this Agreement if the delay or failure is due to causes beyond its reasonable control, such as a strike, blockade, war, act of terrorism, riot, natural disaster, failure or reduction of power or telecommunications or data networks or services, or government act.</p>
                        <p>12.7 - <strong>Export Control</strong>. Each party will comply with all applicable export control laws. Customer represents and warrants that it is not on any government list of prohibited or restricted parties or located in (or a national of) a country subject to a government embargo or that has been designated by the government as a “terrorist supporting” country.</p>
                        <p>12.8 - <strong>Publicity</strong>. Customer agrees that Stark Lab may refer to Customer’s name and trademarks in Stark Lab’s marketing materials and website, including but not limited to displaying the Customer’s logo, solely for the purpose of identifying Customer as a customer of Stark Lab.</p>
                        <p>12.9 - <strong>Amendments; Waivers</strong>. Stark Lab may update the terms and conditions of this Agreement (which may include changes pricing and plans) from time to time with prior notice to Customer in accordance with Section 12.3. No waiver will be implied from conduct or failure to enforce or exercise rights under this Agreement. Waivers must be made in writing and executed by an authorized representative of the waiving party.</p>
                        <p>12.10 - <strong>Severability</strong>. If any provision of this Agreement is found by any court of competent jurisdiction to be unenforceable or invalid, that provision will be limited to the minimum extent necessary so that this Agreement may otherwise remain in effect.</p>
                        <p>12.11 - <strong>No Third-Party Rights</strong>. Nothing in this Agreement confers on any third party the right to enforce any provision of this Agreement.</p>
                        <p>12.12 - <strong>Entire Agreement</strong>. This Agreement represents the parties’ complete and exclusive understanding relating to the Agreement’s subject matter. It supersedes all prior or contemporaneous oral or written communications, proposals and representations with respect to the Stark Lab Technology or any other subject matter covered by this Agreement. The terms of the United Nations Convention on Contracts for the Sale of Goods do not apply to this Agreement. Any terms provided by Customer (including as part of any purchase order or other business form used by Customer) are for administrative purposes only, and have no legal effect.</p>
                    </section>
                </main>
            </div>
        </>
    )
}

export default Tos;