import "./style/general.css";
import Header from "./components/Header";

const App = () => {
  return (
    <div>
      <Header/>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
      <p>hey</p>
   
    </div>
  )
}

export default App;